cruise_keyword_dict = {
"chl":["chlorphyll","chl"],
"chlorophyll":["chlorphyll","chl"],
"chl_hot":["chlorphyll","chl"],
"chloropigment_ctd_hot":["chlorphyll","chl"],
"chl_bottle_hot":["chlorphyll","chl"],
"hplc_chl3_bottle_hot":["chlorphyll","chl"],
"hplc_chl12_bottle_hot":["chlorphyll","chl"],
"hplc_chlplus_bottle_hot":["chlorphyll","chl"],
"hplc_chlb_bottle_hot":["chlorphyll","chl"],
"hplc_chla_bottle_hot":["chlorphyll","chl"],
"hplc_chlc4_bottle_hot":["chlorphyll","chl"],
"hplc_chlda_bottle_hot":["chlorphyll","chl"],
"hplc_mvchla_bottle_hot":["chlorphyll","chl"],
"hplc_dvchla_bottle_hot":["chlorphyll","chl"],
"hplc_dvchla_bottle_hot":["chlorphyll","chl"],
"chlda_cmore":["chlorphyll","chl"],
"chlplus_cmore":["chlorphyll","chl"],
"chlb_cmore":["chlorphyll","chl"],
"dvchla_cmore":["chlorphyll","chl"],
"mvchla_cmore":["chlorphyll","chl"],
"prochl_chisholm":["chlorphyll","chl"],
"chlpig_cmore":["chlorphyll","chl"],
"chlorophyll_c":["chlorphyll","chl"],
"divinyl_chlorophyll_a":["chlorphyll","chl"],
"fluorometric_chlorophyll_a":["chlorphyll","chl"],
"monovinyl_chlorophyll_a":["chlorphyll","chl"],
"chlorophyll_a":["chlorphyll","chl"],
"chlorophyll_b":["chlorphyll","chl"],
"esv_chl":["chlorphyll","chl"],
"chla_amt13":["chlorphyll","chl"],
"chla":["chlorphyll","chl"],
"ctd_chloropigment":["chlorphyll","chl"],
"chl_fl":["chlorphyll","chl"],
"ac_s_chl":["chlorphyll","chl"],

"prochlorococcus":["pro","prochlorococcus"],
"prochloro_abundance":["pro","prochlorococcus"],
"prochloro_diameter":["pro","prochlorococcus"],
"prochloro_carbon_content":["pro","prochlorococcus"],
"prochloro_biomass":["pro","prochlorococcus"],
"prochlorococcus_hot":["pro","prochlorococcus"],
"prochlorococcus_bottle_hot":["pro","prochlorococcus"],
"prochl_chisholm":["pro","prochlorococcus"],
"pbact_chisholm":["pro","prochlorococcus"],

"synechococcus":["syn","synechococcus"],
"synecho_abundance":["syn","synechococcus"],
"synecho_diameter":["syn","synechococcus"],
"synecho_carbon_content":["syn","synechococcus"],
"synecho_biomass":["syn","synechococcus"],
"synechococcus_hot":["syn","synechococcus"],
"synechococcus_bottle_hot":["syn","synechococcus"],
"synchl_chisholm":["syn","synechococcus"],
"synechococcus_abundance_flombaum":["syn","synechococcus"],
"sbact_chisholm":["syn","synechococcus"],

"crocosphaera":["chroco","crocosphaera"],
"croco_abundance":["chroco","crocosphaera"],
"croco_diameter":["chroco","crocosphaera"],
"croco_carbon_content":["chroco","crocosphaera"],
"croco_biomass":["chroco","crocosphaera"],

"picoeukaryote":["picoeuk","picoeukaryote"],
"picoeuk_abundance":["picoeuk","picoeukaryote"],
"picoeuk_diameter":["picoeuk","picoeukaryote"],
"picoeuk_carbon_content":["picoeuk","picoeukaryote"],
"picoeuk_biomass":["picoeuk","picoeukaryote"],
"pico_eukaryote_abundance":["picoeuk","picoeukaryote"],

"sss":["sea surface salinity","sst",'salinity'],
"sea_surface_salinity":["sea surface salinity","sst",'salinity'],
"sea_salinity":["sea surface salinity","sst",'salinity'],

"salinity":["salinity","salt"],
"sal":["salinity","salt"],
"salinity_hot":["salinity","salt"],
"salinity_ctd_hot":["salinity","salt"],
"salinity_ctd_bottle_hot":["salinity","salt"],
"salinity_bottle_hot":["salinity","salt"],
"csal_cmore":["salinity","salt"],
"salinity_ctd":["salinity","salt"],
"esv_salinity":["salinity","salt"],
"csal_ppt_amt13":["salinity","salt"],
"ctd_salinity":["salinity","salt"],
"adjusted_salinity":["salinity","salt"],

"sst":["sea surface temperature","sst"],
"sea_surface_temperature":["sea surface temperature","sst"],
"sea_surface_temp":["sea surface temperature","sst"],
"sea_temperature":["sea surface temperature","sst"],

"temp":["temperature","sea water temperature"],
"temperature":["temperature","sea water temperature"],
"potential_temperature_ctd_hot":["temperature","sea water temperature"],
"temperature_ctd_hot":["temperature","sea water temperature"],
"potential_temperature_ctd_bottle_hot":["temperature","sea water temperature"],
"temperature_ctd_bottle_hot":["temperature","sea water temperature"],
"temperature_potential":["temperature","sea water temperature"],
"temperature_ctd":["temperature","sea water temperature"],
"esv_tempreature":["temperature","sea water temperature"],
"temp_c_amt13":["temperature","sea water temperature"],
"temperature_ctd":["temperature","sea water temperature"],
"ctd_temperature":["temperature","sea water temperature"],
"potential_temperature":["temperature","sea water temperature"],
"temp_flag":["temperature","sea water temperature"],
"ctd_temperature":["temperature","sea water temperature"],


"nitrate":["no3","no3","no_3"],
"no_3":["nitrate","no3","no_3"],

"no3":["nitrate","no3","no_3"],
"nitrate":["no3","no3","no_3"],
"no_3":["nitrate","no3","no_3"],

"fe":["iron"],
"iron":["fe"],

"no3_no2":["no_3","no3","no2","no_2","no3_no2","no2_no3"],

"doc":["disolved organic carbon", "doc"],
"disolved organic carbon":["disolved organic carbon", "doc"],
"doc_bottle_hot":["disolved organic carbon", "doc"],

"dioc":["disolved inorganic carbon", "dioc"],
"dissolved_inorganic_carbon":["disolved inorganic carbon", "dioc"],
"dissolved inorganic carbon":["disolved inorganic carbon", "dioc"],

"po4":["phosphate","p0_4","po_4"],
"po_4":["phosphate","p0_4","po_4"],
"phosphate":["phosphate","p0_4","po_4"],
"phos_cmore":["phosphate","p0_4","po_4"],

"sio4":["silicate","silica","sio4"],
"silicate":["silicate","silica","sio4"],
"sil_cmore":["silicate","silica","sio4"],
"silica_hot":["silicate","silica","sio4"],
"psi":["silicate","silica","sio4"],

"o2":["oxygen","o_2","o2"],
"oxygen":["oxygen","o_2","o2"],
"oxygen_ctd_hot":["oxygen","o_2","o2"],
"oxygen_ctd_bottle_hot":["oxygen","o_2","o2"],
"oxygen_bottle_hot":["oxygen","o_2","o2"],
"coxy_cmore":["oxygen","o_2","o2"],
"boxy_cmore":["oxygen","o_2","o2"],
"dissolved_oxygen":["oxygen","o_2","o2"],
"dissolved_oxygen_ctd":["oxygen","o_2","o2"],
"dissolved_oxygen":["oxygen","o_2","o2"],
"ctd_oxygen":["oxygen","o_2","o2"],
"bottle_oxygen":["oxygen","o_2","o2"],
"oxygen_saturation":["oxygen","o_2","o2"],
}
